// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpi3X1eDDt4v0TV01q7-lN6QOpYBUUiDs',
    appId: '1:281044300755:web:e6419a1200ee0c4501f526',
    messagingSenderId: '281044300755',
    projectId: 'groupyy',
    authDomain: 'groupyy.firebaseapp.com',
    storageBucket: 'groupyy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqtdblUwdy0WhXZBhlBKB3OlDUzRJ4oYk',
    appId: '1:281044300755:android:ecc24379b9720bc701f526',
    messagingSenderId: '281044300755',
    projectId: 'groupyy',
    storageBucket: 'groupyy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT3dbib1-8zJTITUxplgUVIwfyQzyIUjw',
    appId: '1:281044300755:ios:eef4519bb9cf1d7e01f526',
    messagingSenderId: '281044300755',
    projectId: 'groupyy',
    storageBucket: 'groupyy.appspot.com',
    iosBundleId: 'com.example.groupieee',
  );
}
